import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div>
          <img src="/logo.svg"></img>
        </div>
        <div>
          <input type="checkbox" class="toggler" />
          <div class="hamburger">
            <div></div>
          </div>
          <div class="menu">
            <div>
              <ul>
                <li>
                  <a href="#">Home</a>
                </li>
                <li>
                  <a href="#">About</a>
                </li>
                <li>
                  <a href="#">Services</a>
                </li>
                <li>
                  <a href="#">Contact</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </header>
      <main>
        <section className="container hero">
          <div>
            <img src="/Hero.svg"></img>
          </div>
          <div>
            <img src="/Hero_Photo.png"></img>
          </div>
        </section>

        <section className="container book">
          <h1>BOOK AN APPOUNTMENT</h1>
          <h3>Send your data for book</h3>
          <form>
            <input placeholder="Name"></input>
            <input placeholder="Phone"></input>
            <button>SEND</button>
          </form>
        </section>
      </main>
      <footer>
        <img src="/images/footer.png" className="footer_flower"></img>
      </footer>
    </>
  );
}
